twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator


    # Variables globales 
    globals:
            name_site: 'Playmothek'
            playmo : 'Playmobil'
            admin : 'Interface Administrateur'

when@test:
    twig:
        strict_variables: true
